[workspace]
members = ["daead", "mac", "prf", "signature", "testing", "testutil", "tink"]

# Patch dependencies on tink crates so that they refer to the versions within this same repository.
[patch.crates-io]
tink = { path = "tink" }
tink-daead = { path = "daead" }
tink-mac = { path = "mac" }
tink-prf = { path = "prf" }
tink-signature = { path = "signature" }
tink-testing-server = { path = "testing" }
tink-testutil = { path = "testutil" }
