# Configuration used for dependency checking with cargo-deny.
#
# For further details on all configuration options see:
# https://embarkstudios.github.io/cargo-deny/checks/cfg.html
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[sources]
allow-git = [ "https://github.com/daviddrysdale/ed25519-dalek" ]

# Deny all advisories unless explicitly ignored.
[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = []

# Deny multiple versions unless explicitly skipped.
[bans]
multiple-versions = "deny"
wildcards = "allow"

######################################

# Old versions of crates pulled in (transitively) by rusoto_*(v0.47.0)
[[bans.skip]]
name = "cfg-if"
version = "0.1.10"
[[bans.skip]]
name = "core-foundation"
version = "=0.7.0"
[[bans.skip]]
name = "core-foundation-sys"
version = "=0.7.0"
[[bans.skip]]
name = "pin-project"
version = "=0.4.26"
[[bans.skip]]
name = "pin-project-internal"
version = "=0.4.26"
[[bans.skip]]
name = "pin-project-lite"
version = "=0.1.10"
[[bans.skip]]
name = "security-framework"
version = "=0.4.4"
[[bans.skip]]
name = "security-framework-sys"
version = "=0.4.3"

# hyper-rustls(v0.22.1) => rustls => ring(v0.16.20) => spin(v0.5.2)
[[bans.skip]]
name = "spin"
version = "0.5.2"

######################################

# List of allowed licenses.
# For more detailed information see http://go/thirdpartylicenses.
[licenses]
allow = [
  "Apache-2.0",
  "ISC",
  "MIT",
  "OpenSSL",
  "BSD-3-Clause",
]
copyleft = "deny"

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 3171872035 }]
