[package]
name = "tink-mac"
version = "0.1.0"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"

[dependencies]
prost = "*"
tink = "*"
tink-prf = "*"

[dev-dependencies]
hex = "*"
lazy_static = "*"
maplit = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tink-prf = "*"
tink-testutil = "*"
