[package]
name = "tink"
version = "0.1.0"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"

[dependencies]
lazy_static = "*"
prost = "*"
rand = "*"

[build-dependencies]
prost-build = "*"

[dev-dependencies]
tink-testutil = "*"
