[package]
name = "tink-testutil"
version = "0.1.0"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"

[dependencies]
prost = "*"
rand = "*"
serde = { version = "*", features = ["derive"] }
# Depending on tink-testutil will turn on the `insecure` feature of `tink`.
tink = { version = "*", features = ["insecure"] }

[dev-dependencies]
serde_json = "*"
