[package]
name = "tink-signature"
version = "0.1.0"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"

[dependencies]
ed25519-dalek = "*"
elliptic-curve = "*"
generic-array = "*"
# TODO  remove this:
hex = "*"
p256 = { version = "*", features = ["ecdsa"] }
prost = "*"
rand = "*"
signature = "*"
tink = "*"

[dev-dependencies]
base64 = "*"
hex = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tink-mac = "*"
tink-testutil = "*"
